[package]
name = "clipferry"
version = "0.1.0"
edition = "2024"
license = "GPL-3.0-only"
description = "A native Windows LAN file clipboard"
repository = "https://github.com/micky-meecky/ClipFerry"

[dependencies]

[lints.rust]
unsafe_op_in_unsafe_fn = "deny"

[lints.clippy]
pedantic = { level = "warn", priority = -1 }
